
- name: config_ops445.yml
  hosts: vmlab
  user: student
  become: yes

  tasks:
   - name: Update apache
     ansible.builtin.yum:
      name: httpd
      state: latest 

   - name: Gather package facts
     package_facts:
      manager: auto

   - name: Install EPEL if not installed
     yum: 
      name: epel-release
      state: latest
     when: "'epel-release' not in ansible_facts.packages"

   - name: Remove tree package
     yum:
      name: tree
      state: absent 

   - name: Change host name
     hostname: 
       name: vdong4_remote

   - name: Create new user
     user:
        name: vdong4_user
        password: "{{ 'password' | password_hash('sha512')}}"
        shell: /bin/bash
        state: present

   -  name: Give user sudo access
      user:
       name: vdong4_user
       groups: wheel
       append: yes 

   -  name: copy public key for vdong4_user's folder
      copy:
        src: ~/.ssh/id_rsa.pub
        dest: /home/vdong4_user/.ssh/authorized_keys
        owner: vdong4_user
        group: vdong4_user
        mode: 0600

   - name: Create folder loop
     file:
      path: "/home/vdong4_user/ops445/{{ item }}"
      state: directory
      owner: vdong4_user
      group: vdong4_user
      mode: 0775
     loop:
      - lab1
      - lab2
      - lab3
      - lab4
      - lab5
      - lab6
      - lab7
      - lab8
      

   
  



   